AWSTemplateFormatVersion: 2010-09-09
Description: Creating AWS EC2 Instance with parameters wth AZ with SSM

Parameters:
  MyKeyName:
    Description: Select the key name from the list
    Type: AWS::EC2::KeyPair::KeyName
  MyAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: us-east-2a
    AllowedValues:
      - us-east-2a
      - us-east-2b
      - us-east-2c
  MyInstanceType:
    Description: Select ec2 instance type from SSM
    Type: AWS::SSM::Parameter::Value<String>


Resources:
  DemoEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05d72852800cbf29e
      InstanceType:
        Ref: MyInstanceType
      KeyName: 
        Ref: MyKeyName
      SecurityGroups:
      - default
      - Ref: SSHSecurityGroup
      AvailabilityZone:
        Ref: MyAvailabilityZone
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH SG
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: 'tcp'
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
